package org.rocstreaming.rocdroid


const val UPDATE_CONNECTION = "ACTION_UPDATE_ROC_CONNECTION"
const val UPDATE_IS_CONNECTED = "ACTION_UPDATE_IS_ROC_CONNECTED"
const val UPDATE_DISPLAY_NAME = "ACTION_UPDATE_ROC_DISPLAY_NAME"
const val UPDATE_STREAM = "ACTION_ROC_UPDATE_STREAM"
const val UPDATE_MUTE = "ACTION_ROC_UPDATE_MUTE"
const val INTENT_SEND_UPDATE = "SEND_ROC_UPDATE"

const val PREFIX = "ROC_DROID_"
const val CHANNEL_ID = "${PREFIX}NOTIFICATION_CHANNEL"

// Service
const val START = "${PREFIX}START"
const val START_NO_SEND = "${PREFIX}START_NO_SEND"
const val MUTE = "${PREFIX}MUTE"
const val DEAF = "${PREFIX}DEAF"
const val SEND = "${PREFIX}SEND"
const val RECV = "${PREFIX}RECEIVE"
const val CONNECT = "${PREFIX}CONNECT"
const val DISCONNECT = "${PREFIX}DISCONNECT"
const val SETTINGS = "${PREFIX}SETTINGS"
const val STOP = "${PREFIX}STOP"

// UI
const val UPDATE = "${PREFIX}UPDATE"
const val TRANSMISSION = "${PREFIX}TRANSMISSION"
const val CONTROL = "${PREFIX}CONTROL"


const val UID = "USER_ID"
const val CONTROL_NOTIFICATION_ID = 0x10
const val SEND_NOTIFICATION_ID = 0x20
const val RECEIVE_NOTIFICATION_ID = 0x30

const val SAMPLE_RATE = 44100
const val BUFFER_SIZE = 100

const val REQUEST_RECORD_AUDIO_PERMISSION = 200